/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Michael Fiedler     - initial API and implementation for Bugzilla adapter
 *     Jad El-khoury       - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *     Jim Amsden          - Support for UI Preview (494303)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
package se.kth.vis.services;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.FormParam;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.core.UriBuilder;

import org.apache.wink.json4j.JSONObject;
import org.eclipse.lyo.oslc4j.provider.json4j.JsonHelper;
import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.annotation.OslcCreationFactory;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialog;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDialogs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.Compact;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;
import org.eclipse.lyo.oslc4j.core.model.Preview;
import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;

import se.kth.vis.Robot1Manager;
import se.kth.vis.Robot1Constants;
import se.kth.vis.resources.Nsp1Constants;
import se.kth.vis.resources.Nsp1Constants;
import se.kth.vis.servlet.ServiceProviderCatalogSingleton;
import se.kth.vis.resources.Action;
import se.kth.vis.resources.PerformedAction;
import se.kth.vis.resources.PlannedAction;

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code
@OslcService(Nsp1Constants.WAREHOUSE_DOMAIN)
@Path("service2/performedActions")
public class ServiceProviderService2
{
    @Context private HttpServletRequest httpServletRequest;
    @Context private HttpServletResponse httpServletResponse;
    @Context private UriInfo uriInfo;

    // Start of user code class_attributes
    // End of user code

    // Start of user code class_methods
    // End of user code

    public ServiceProviderService2()
    {
        super();
    }

    @OslcQueryCapability
    (
        title = "QueryCapability1",
        label = "QueryCapability1",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + Nsp1Constants.PATH_PERFORMEDACTION,
        resourceTypes = {Nsp1Constants.TYPE_PERFORMEDACTION},
        usages = {}
    )
    @GET
    @Path("query")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    public PerformedAction[] queryPerformedActions(
                                                    
                                                     @QueryParam("oslc.where") final String where,
                                                     @QueryParam("page") final String pageString,
                                                    @QueryParam("limit") final String limitString) throws IOException, ServletException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryPerformedActions
        // Here additional logic can be implemented that complements main action taken in Robot1Manager
        // End of user code

        final List<PerformedAction> resources = Robot1Manager.queryPerformedActions(httpServletRequest, where, page, limit);
        return resources.toArray(new PerformedAction [resources.size()]);
    }

    @GET
    @Path("query")
    @Produces({ MediaType.TEXT_HTML })
    public Response queryPerformedActionsAsHtml(
                                    
                                       @QueryParam("oslc.where") final String where,
                                       @QueryParam("page") final String pageString,
                                    @QueryParam("limit") final String limitString) throws ServletException, IOException
    {
        int page=0;
        int limit=20;
        if (null != pageString) {
            page = Integer.parseInt(pageString);
        }
        if (null != limitString) {
            limit = Integer.parseInt(limitString);
        }

        // Start of user code queryPerformedActionsAsHtml
        // End of user code

        final List<PerformedAction> resources = Robot1Manager.queryPerformedActions(httpServletRequest, where, page, limit);

        if (resources!= null) {
            httpServletRequest.setAttribute("resources", resources);
            // Start of user code queryPerformedActionsAsHtml_setAttributes
            // End of user code

            httpServletRequest.setAttribute("queryUri",
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
            if (resources.size() > limit) {
                resources.remove(resources.size() - 1);
                httpServletRequest.setAttribute("nextPageUri",
                        uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
            }
            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/vis/performedactionscollection.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{performedActionId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    public PerformedAction getPerformedAction(
                @PathParam("performedActionId") final String performedActionId
        ) throws IOException, ServletException, URISyntaxException
    {
        // Start of user code getResource_init
        // End of user code

        final PerformedAction aPerformedAction = Robot1Manager.getPerformedAction(httpServletRequest, performedActionId);

        if (aPerformedAction != null) {
            // Start of user code getPerformedAction
            // End of user code
            httpServletResponse.addHeader(Robot1Constants.HDR_OSLC_VERSION, Robot1Constants.OSLC_VERSION_V2);
            return aPerformedAction;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{performedActionId}")
    @Produces({ MediaType.TEXT_HTML })
    public Response getPerformedActionAsHtml(
        @PathParam("performedActionId") final String performedActionId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getPerformedActionAsHtml_init
        // End of user code

        final PerformedAction aPerformedAction = Robot1Manager.getPerformedAction(httpServletRequest, performedActionId);

        if (aPerformedAction != null) {
            httpServletRequest.setAttribute("aPerformedAction", aPerformedAction);
            // Start of user code getPerformedActionAsHtml_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/vis/performedaction.jsp");
            rd.forward(httpServletRequest,httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{performedActionId}")
    @Produces({OslcMediaType.APPLICATION_X_OSLC_COMPACT_XML})
    public Compact getPerformedActionCompact(
        @PathParam("performedActionId") final String performedActionId
        ) throws ServletException, IOException, URISyntaxException
    {
        String iconUri = OSLC4JUtils.getPublicURI() + "/images/ui_preview_icon.gif";
        String smallPreviewHintHeight = "10em";
        String smallPreviewHintWidth = "45em";
        String largePreviewHintHeight = "20em";
        String largePreviewHintWidth = "45em";

        // Start of user code getPerformedActionCompact_init
        //TODO: adjust the preview height & width values from the default values provided above.
        // End of user code

        final PerformedAction aPerformedAction = Robot1Manager.getPerformedAction(httpServletRequest, performedActionId);

        if (aPerformedAction != null) {
            final Compact compact = new Compact();

            compact.setAbout(aPerformedAction.getAbout());
            compact.setTitle(aPerformedAction.toString());

            compact.setIcon(new URI(iconUri));

            //Create and set attributes for OSLC preview resource
            final Preview smallPreview = new Preview();
            smallPreview.setHintHeight(smallPreviewHintHeight);
            smallPreview.setHintWidth(smallPreviewHintWidth);
            smallPreview.setDocument(UriBuilder.fromUri(aPerformedAction.getAbout()).path("smallPreview").build());
            compact.setSmallPreview(smallPreview);

            //Use the HTML representation of a change request as the large preview as well
            final Preview largePreview = new Preview();
            largePreview.setHintHeight(largePreviewHintHeight);
            largePreview.setHintWidth(largePreviewHintWidth);
            largePreview.setDocument(aPerformedAction.getAbout());
            compact.setLargePreview(largePreview);
            httpServletResponse.addHeader(Robot1Constants.HDR_OSLC_VERSION, Robot1Constants.OSLC_VERSION_V2);
            return compact;
        }
        throw new WebApplicationException(Status.NOT_FOUND);
    }

    @GET
    @Path("{performedActionId}/smallPreview")
    @Produces({ MediaType.TEXT_HTML })
    public void getPerformedActionAsHtmlSmallPreview(
        @PathParam("performedActionId") final String performedActionId
        ) throws ServletException, IOException, URISyntaxException
    {
        // Start of user code getPerformedActionAsHtmlSmallPreview_init
        // End of user code

        final PerformedAction aPerformedAction = Robot1Manager.getPerformedAction(httpServletRequest, performedActionId);

        if (aPerformedAction != null) {
            httpServletRequest.setAttribute("aPerformedAction", aPerformedAction);
            // Start of user code getPerformedActionAsHtmlSmallPreview_setAttributes
            // End of user code

            RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/vis/performedactionsmallpreview.jsp");
            httpServletResponse.addHeader(Robot1Constants.HDR_OSLC_VERSION, Robot1Constants.OSLC_VERSION_V2);
            rd.forward(httpServletRequest, httpServletResponse);
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
}
