/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/

package se.kth.vis.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;

// Start of user code imports
// End of user code

public interface Nsp1Constants
{
    // Start of user code user constants
    // End of user code

    public static String WAREHOUSE_DOMAIN = "http://your.organisation.domain/nsp1#";
    public static String WAREHOUSE_NAMSPACE = "http://your.organisation.domain/nsp1#";
    public static String WAREHOUSE_NAMSPACE_PREFIX = "nsp1";

    public static String ACTION = "Action";
    public static String PATH_ACTION = "action";
    public static String TYPE_ACTION = WAREHOUSE_NAMSPACE + ACTION;
    public static String NSP1OBJECT = "Nsp1Object";
    public static String PATH_NSP1OBJECT = "nsp1Object";
    public static String TYPE_NSP1OBJECT = WAREHOUSE_NAMSPACE + NSP1OBJECT;
    public static String PERFORMEDACTION = "PerformedAction";
    public static String PATH_PERFORMEDACTION = "performedAction";
    public static String TYPE_PERFORMEDACTION = WAREHOUSE_NAMSPACE + PERFORMEDACTION;
    public static String PLACE = "Place";
    public static String PATH_PLACE = "place";
    public static String TYPE_PLACE = WAREHOUSE_NAMSPACE + PLACE;
    public static String PLAN = "Plan";
    public static String PATH_PLAN = "plan";
    public static String TYPE_PLAN = WAREHOUSE_NAMSPACE + PLAN;
    public static String PLANNEDACTION = "PlannedAction";
    public static String PATH_PLANNEDACTION = "plannedAction";
    public static String TYPE_PLANNEDACTION = WAREHOUSE_NAMSPACE + PLANNEDACTION;
    public static String ROBOT = "Robot";
    public static String PATH_ROBOT = "robot";
    public static String TYPE_ROBOT = WAREHOUSE_NAMSPACE + ROBOT;
    public static String WAYPOINT = "WayPoint";
    public static String PATH_WAYPOINT = "wayPoint";
    public static String TYPE_WAYPOINT = WAREHOUSE_NAMSPACE + WAYPOINT;
}
